Datasets:
  root_path: "/home/croc/Documenti/Trajectories"
  map_folder: "map_gt"
  data_folder: "Datasets/TUM Format"
  out_eva_folder: "trajectories"
  Scenarios:
    Corridor_A:
      folder_name: "excasi"
      map_name: "excasi"
    Corridor_B:
      folder_name: "corridor_valigi"
      map_name: "corridorValigi"
    Airport:
      folder_name: "airport"
      map_name: "airport_small"
